'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,Star,Goal,MessageSquare,MapPin,Search,Check,Trash2,Pencil,ArrowRight,Trophy,CalendarDays,Shield,Loader2,LogOut} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {teams,matches,standings,rankStatus,RecordItem} from '@/lib/football';
import {MotionRoot,Reveal,ClubCard,Count,motion,AnimatePresence,AnimatedTab} from '@/components/kurve-motion';
import {AuthGate} from '@/components/auth-gate';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
type Team=typeof teams[number];
function Badge({id,large=false}:{id:string;large?:boolean}){const t=teams.find(t=>t.id===id)!;return <span className={'club-mark '+(large?'large':'')} style={{'--club':t.color} as React.CSSProperties}>{id}</span>}
export default function Home(){return <MotionRoot><AuthGate>{(logout,expired)=><Hub onLogout={logout} onExpired={expired}/>}</AuthGate></MotionRoot>}
function Hub({onLogout,onExpired}:{onLogout:()=>Promise<void>;onExpired:()=>void}){const [tab,setTab]=useState('teams'),[query,setQuery]=useState(''),[records,setRecords]=useState<RecordItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Team|null>(null),[comment,setComment]=useState(''),[edit,setEdit]=useState<string|undefined>(),[tip,setTip]=useState<typeof matches[number]|null>(null),[home,setHome]=useState(''),[away,setAway]=useState('');
async function refresh(){const r=await fetch('/api/records');if(r.status===401){onExpired();throw Error('Bitte melde dich an.')}if(!r.ok)throw Error('Deine gespeicherten Daten sind gerade nicht erreichbar.');setRecords(await r.json())}
useEffect(()=>{refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
async function mutate(body:object,remove=false){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/records',{method:remove?'DELETE':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.status===401){onExpired();return false}if(!r.ok){const data=await r.json() as {error?:string};throw Error(data.error||'Die Änderung konnte nicht gespeichert werden.')}await refresh();setNotice(remove?'Eintrag entfernt.':'Gespeichert.');return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
const fav=records.filter(r=>r.kind==='favorite'),tips=records.filter(r=>r.kind==='tip'),comments=records.filter(r=>r.kind==='comment');
const isFav=(id:string)=>fav.some(r=>r.target===id);
function favorite(id:string){return isFav(id)?mutate({id:'favorite-'+id},true):mutate({kind:'favorite',target:id,value:'1'})}
function openTeam(t:Team){setSelected(t);setComment('');setEdit(undefined)}
function openTip(m:typeof matches[number]){const prev=tips.find(t=>t.target===m.id)?.value.split(':');setHome(prev?.[0]||'');setAway(prev?.[1]||'');setTip(m)}
const filtered=teams.filter(t=>(tab!=='favorites'||isFav(t.id))&&`${t.name} ${t.city}`.toLowerCase().includes(query.toLowerCase()));
return <div className="shell"><header className="top"><a href="/" className="brand"><span className="brand-icon"><Goal size={26}/></span>NBA HUB</a><div className="top-right"><span className="season">SAISON 2026/27</span><span className="account-name">admin</span><Button className="logout-button" variant="ghost" disabled={busy} onClick={async()=>{setBusy(true);await onLogout();setBusy(false)}}><LogOut/>Logout</Button></div></header><main><Reveal className="intro"><div><div className="eyebrow">30 TEAMS. EINE LIGA.</div><h1>Deine NBA. <span className="heading-accent">Dein Hub.</span></h1><p>Entdecke die Teams. Setze deine Tipps. Verfolge die Saison.</p></div><div className="league-label"><Trophy size={25}/><div><strong>NBA</strong><small>USA &amp; Kanada · 2026/27</small></div></div></Reveal>
<section className="overview"><Reveal className="match-feature" delay={.08}><div className="feature-top"><span><CalendarDays size={15}/> IM FOKUS · SAISONSTART</span><span>21. OKT · 04:00 UHR</span></div><div className="feature-caption">DAS DUELL IM FOKUS <ArrowUpRight size={16}/></div><div className="featured-teams"><div><Badge id="LAL" large/><strong>Los Angeles Lakers</strong></div><span className="versus">VS</span><div><Badge id="GSW" large/><strong>Golden State Warriors</strong></div></div><div className="feature-bottom"><span>Crypto.com Arena, Los Angeles</span><Button onClick={()=>openTip(matches[1])}>Jetzt tippen <ArrowUpRight/></Button></div></Reveal><Reveal className="personal" delay={.16}><div className="eyebrow">DEINE NBA</div><h2>Alles auf einen Blick.</h2><div className="metrics"><button onClick={()=>setTab('favorites')}><Star/><strong><Count value={fav.length}/></strong><span>Favoriten</span></button><button onClick={()=>setTab('tips')}><Goal/><strong><Count value={tips.length}/></strong><span>Deine Tipps</span></button><button onClick={()=>setTab('comments')}><MessageSquare/><strong><Count value={comments.length}/></strong><span>Kommentare</span></button></div><p><Shield size={14}/> Dein privater Fanbereich · dauerhaft gespeichert</p></Reveal></section>
{error&&<div className="error" role="alert">{error} <button onClick={()=>{setError('');refresh().catch(e=>setError(e.message))}}>Erneut laden</button></div>}<div className="sr-only" role="status">{notice}</div>
<Tabs value={tab} onValueChange={setTab}><div className="navigation"><TabsList variant="line">{[{id:'teams',label:'Teams',icon:Shield},{id:'ranking',label:'Standings',icon:Trophy},{id:'favorites',label:'Favoriten',icon:Star},{id:'tips',label:'Meine Tipps',icon:Goal},{id:'comments',label:'Kommentare',icon:MessageSquare}].map(item=><TabsTrigger key={item.id} value={item.id}>{tab===item.id&&<motion.span className="tab-active-pill" layoutId="active-tab" transition={{type:'spring',stiffness:400,damping:35}}/>}<span className="tab-label"><item.icon/>{item.label}{item.id==='teams'&&<span className="count">30</span>}</span></TabsTrigger>)}</TabsList><span className="saved-status">{loading?<><Loader2 size={14}/> Laden …</>:notice?<><Check size={14}/>{notice}</>:<>Saison 2026/27</>}</span></div>
<AnimatedTab value="ranking"><div className="section-title"><div><h2>Die NBA in Zahlen.</h2><p>Standings · Saison 2026/27 · vor dem Saisonstart</p></div><span className="pill">30 Teams</span></div><div className="ranking-summary"><Trophy/><div><strong>Die neue Saison steht bevor</strong><p>Alle Teams starten bei 0–0 · Demo-Daten bis ein Live-Feed verbunden ist</p></div><span>2026/27</span></div><div className="leaderboard"><Table><TableHeader><TableRow><TableHead scope="col">Platz</TableHead><TableHead scope="col">Team</TableHead><TableHead scope="col" title="Spiele">Sp.</TableHead><TableHead scope="col" title="Siege und Niederlagen">S / N</TableHead><TableHead scope="col">Siegquote</TableHead><TableHead scope="col">Serie</TableHead><TableHead scope="col">Status</TableHead><TableHead scope="col">Nächstes Spiel</TableHead></TableRow></TableHeader><TableBody>{standings.map(row=>{const team=teams.find(t=>t.id===row.id)!;const status=rankStatus(row.rank);const next=matches.find(m=>(m.home===row.id||m.away===row.id)&&Date.parse(m.date)>Date.now());const opponent=next?teams.find(t=>t.id===(next.home===row.id?next.away:next.home)):null;return <TableRow key={row.id} className={isFav(row.id)?'ranking-favorite':''}><TableCell><span className={'rank-number '+status.tone}>{row.rank.toString().padStart(2,'0')}</span></TableCell><TableCell><button className="ranking-team" onClick={()=>openTeam(team)}><Badge id={row.id}/><strong>{team.name}</strong>{isFav(row.id)&&<Star size={14} fill="currentColor"/>}</button></TableCell><TableCell>{row.played}</TableCell><TableCell>{row.won} / {row.lost}</TableCell><TableCell><strong className="ranking-points">{row.winPct.toFixed(3)}</strong></TableCell><TableCell>{row.streak}</TableCell><TableCell><span className={'rank-status '+status.tone}>{status.label}</span></TableCell><TableCell>{next&&opponent?<button className="next-match" onClick={()=>openTip(next)}><strong>{next.home===row.id?'H':'A'} · {opponent.name}<ArrowUpRight size={14}/></strong><span>{new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Berlin'}).format(new Date(next.date))} Uhr</span></button>:<span className="no-next">Kein Termin hinterlegt</span>}</TableCell></TableRow>})}</TableBody></Table></div><div className="ranking-notes"><p>H = Heimspiel · A = Auswärtsspiel · Zeiten in Deutschland. Klicke auf ein Spiel, um deinen Tipp abzugeben.</p><p>NBA-Format: Plätze 1–6 direkte Playoffs, Plätze 7–10 Play-In. Die Anzeige ist vor Saisonbeginn alphabetisch sortiert.</p><p>Kein Live-Feed. <a href="https://www.nba.com/standings" target="_blank" rel="noreferrer">Offizielle NBA-Standings ↗</a></p></div></AnimatedTab>
{['teams','favorites'].map(view=><AnimatedTab key={view} value={view}><div className="section-title"><div><h2>{view==='teams'?'Die NBA-Teams':'Deine Favoriten'}</h2><p>{view==='teams'?'Alle 30 Franchises, Arenen und deine nächsten Favoriten.':'Deine Teams, direkt im Blick.'}</p></div><label className="search"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Team suchen …" aria-label="Team suchen"/></label></div><div className="team-grid"><AnimatePresence initial={true}>{filtered.map((t,i)=><ClubCard key={t.id} index={i} color={t.color}><div className="card-top"><Badge id={t.id}/><motion.button whileTap={{scale:.8}} className={'favorite '+(isFav(t.id)?'active':'')} disabled={loading||busy} aria-label={`${t.name} ${isFav(t.id)?'aus Favoriten entfernen':'favorisieren'}`} aria-pressed={isFav(t.id)} onClick={()=>favorite(t.id)}><Star size={20} fill={isFav(t.id)?'currentColor':'none'}/></motion.button></div><button className="team-title" onClick={()=>openTeam(t)}>{t.name}</button><div className="city"><MapPin size={14}/>{t.city}</div><div className="team-number" aria-hidden="true">{t.id}</div><div className="card-bottom"><span>{t.stadium}</span><button onClick={()=>openTeam(t)} aria-label={`${t.name} ansehen`}><ArrowUpRight size={20}/></button></div></ClubCard>)}</AnimatePresence></div>{filtered.length===0&&<div className="empty"><Star/><h3>{query?'Kein Team gefunden.':'Deine Favoritenliste ist noch leer.'}</h3><p>{query?'Versuche einen anderen Namen.':'Markiere Teams mit dem Stern, um sie hier zu sammeln.'}</p><Button variant="outline" onClick={()=>{setQuery('');setTab('teams')}}>Alle Teams ansehen</Button></div>}</AnimatedTab>)}
<AnimatedTab value="tips"><div className="section-title"><div><h2>Dein Tipp zählt.</h2><p>Demo-Spielplan zum Saisonstart · Zeiten in Deutschland</p></div><span className="pill">{tips.length} / {matches.length} getippt</span></div><div className="match-list">{matches.map(m=>{const value=tips.find(t=>t.target===m.id);const locked=Date.now()>=Date.parse(m.date);return <article className="match-row" key={m.id}><span className="match-date">{new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Berlin'}).format(new Date(m.date))}</span><div className="match-clubs"><Badge id={m.home}/><span>{teams.find(t=>t.id===m.home)?.name}</span><b>vs.</b><span>{teams.find(t=>t.id===m.away)?.name}</span><Badge id={m.away}/></div><Button variant={value?'default':'outline'} disabled={loading||busy||locked} onClick={()=>openTip(m)}>{locked?'Geschlossen':value?value.value+' · Bearbeiten':'Tipp abgeben'}</Button>{value&&<button disabled={busy||locked} aria-label="Tipp entfernen" onClick={()=>mutate({id:value.id},true)}><Trash2 size={16}/></button>}</article>})}</div><p className="small-note">Tipps können bis zum Tip-off geändert werden. Kein Geldeinsatz.</p></AnimatedTab>
<AnimatedTab value="comments"><div className="section-title"><div><h2>Deine Stimme zur Liga.</h2><p>Gedanken und Kommentare zu deinen Teams.</p></div><Button onClick={()=>openTeam(teams[0])}>Kommentar erstellen <MessageSquare/></Button></div>{comments.length===0?<div className="empty"><MessageSquare/><h3>Noch kein Kommentar.</h3><p>Öffne ein Team und halte deine Meinung fest.</p></div>:<div className="comment-list">{comments.map(c=><article className="comment" key={c.id}><div><Badge id={c.target}/><strong>{teams.find(t=>t.id===c.target)?.name}</strong><small>{new Date(c.updated).toLocaleDateString('de-DE')}</small></div><p>{c.value}</p><Button variant="ghost" onClick={()=>{setSelected(teams.find(t=>t.id===c.target)!);setComment(c.value);setEdit(c.id)}}><Pencil/>Bearbeiten</Button><Button variant="ghost" disabled={busy} onClick={()=>mutate({id:c.id},true)}><Trash2/>Entfernen</Button></article>)}</div>}</AnimatedTab></Tabs>
<footer><span className="footer-brand">NBA HUB <span>Für die Liga.</span></span><p>Unabhängiges Fanprojekt · Demo-Daten · Kein Live-Feed<br/><a href="https://www.nba.com/teams" target="_blank" rel="noreferrer">Offizielle NBA-Teams</a><span> · </span><a href="https://www.nba.com/schedule" target="_blank" rel="noreferrer">Offizieller Spielplan ↗</a></p></footer></main>
<Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="team-dialog"><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>Teamprofil und deine Kommentare</DialogDescription>{selected&&<><div className="detail-heading"><Badge id={selected.id} large/><div><strong>{selected.city}</strong><p>{selected.stadium}</p></div><Button disabled={loading||busy} variant="outline" onClick={()=>favorite(selected.id)}><Star fill={isFav(selected.id)?'currentColor':'none'}/>{isFav(selected.id)?'Gemerkt':'Merken'}</Button></div><label className="form-label" htmlFor="club-select">Team</label><select id="club-select" value={selected.id} onChange={e=>openTeam(teams.find(t=>t.id===e.target.value)!)}>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><form onSubmit={async e=>{e.preventDefault();if(await mutate({kind:'comment',target:selected.id,value:comment,id:edit})){setComment('');setEdit(undefined)}}}><label className="form-label" htmlFor="comment">{edit?'Kommentar bearbeiten':'Was denkst du über das Team?'}</label><Textarea id="comment" placeholder="Deine Einschätzung, dein Highlight, deine Meinung …" required maxLength={1500} value={comment} onChange={e=>setComment(e.target.value)}/><div className="form-actions"><small>{comment.length}/1500</small><Button disabled={busy||loading||!comment.trim()} type="submit">{busy?'Speichern …':edit?'Änderung speichern':'Kommentar speichern'}</Button></div></form>{error&&<p role="alert" className="error">{error}</p>}<div className="detail-comments">{comments.filter(c=>c.target===selected.id).map(c=><div key={c.id}><p>{c.value}</p><Button variant="ghost" onClick={()=>{setComment(c.value);setEdit(c.id)}}><Pencil/>Bearbeiten</Button><Button variant="ghost" disabled={busy} onClick={()=>mutate({id:c.id},true)}><Trash2/>Entfernen</Button></div>)}</div></>}</DialogContent></Dialog>
<Dialog open={!!tip} onOpenChange={v=>{if(!v)setTip(null)}}><DialogContent><DialogTitle>Wie geht das Spiel aus?</DialogTitle><DialogDescription>Dein NBA-Ergebnistipp. Änderbar bis zum Tip-off.</DialogDescription>{tip&&<form onSubmit={async e=>{e.preventDefault();if(await mutate({kind:'tip',target:tip.id,value:`${Number(home)}:${Number(away)}`}))setTip(null)}}><div className="score-entry"><label><Badge id={tip.home}/><span>{teams.find(t=>t.id===tip.home)?.name}</span><Input type="number" aria-label="Punkte Heimteam" min="0" max="250" required value={home} onChange={e=>setHome(e.target.value)}/></label><b>:</b><label><Badge id={tip.away}/><span>{teams.find(t=>t.id===tip.away)?.name}</span><Input type="number" aria-label="Punkte Auswärtsteam" min="0" max="250" required value={away} onChange={e=>setAway(e.target.value)}/></label></div>{error&&<p role="alert" className="error">{error}</p>}<Button className="w-full" disabled={busy||loading} type="submit">{busy?'Speichern …':'Tipp speichern'}<Check/></Button></form>}</DialogContent></Dialog></div>}
