'use client';
import {useEffect,useState,ReactNode} from 'react';
import {Goal,LockKeyhole,ArrowRight,Loader2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Reveal} from '@/components/kurve-motion';
import {Input} from '@/components/ui/input';
export function AuthGate({children}:{children:(logout:()=>Promise<void>,expired:()=>void)=>ReactNode}){
 const [status,setStatus]=useState<'loading'|'signedout'|'signedin'|'error'>('loading');
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function check(){try{const r=await fetch('/api/auth',{cache:'no-store'});if(!r.ok)throw Error('Deine Anmeldung konnte nicht geprüft werden.');const data=await r.json() as {authenticated:boolean};setStatus(data.authenticated?'signedin':'signedout')}catch(e){setError((e as Error).message);setStatus('error')}}
 useEffect(()=>{check();const focus=()=>{check()};window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus)},[]);
 async function logout(){setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'DELETE'});if(!r.ok)throw Error('Abmelden fehlgeschlagen. Bitte versuche es erneut.');setPassword('');setStatus('signedout')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(status==='signedin')return <>{error&&<div className="auth-error" role="alert">{error}</div>}{children(logout,()=>{setPassword('');setStatus('signedout');setError('Deine Sitzung ist abgelaufen. Bitte melde dich erneut an.')})}</>;
 return <div className="login-page"><div className="login-brand"><Goal size={32}/><span>NBA HUB</span></div><div className="login-layout"><Reveal className="login-story"><div className="eyebrow">DEIN SPIEL. DEINE LEIDENSCHAFT.</div><h2>Hier schlägt<br/>dein <span>Basketballherz.</span></h2><p>Deine Teams. Deine Tipps. Deine Stimme.<br/>Die NBA an einem Ort.</p><div className="login-wordmark" aria-hidden="true">NBA<span>.</span></div><div className="login-story-foot"><span>NBA</span><span>SAISON 2026/27</span></div></Reveal><Reveal className="login-card" delay={.12}><span className="login-lock"><LockKeyhole size={24}/></span><div className="eyebrow">DEIN NBA HUB</div><h1>Willkommen zurück<span>.</span></h1><p>Melde dich an, um deine Teams, Tipps und Kommentare zu verwalten.</p>{status==='loading'?<div className="login-loading" role="status"><Loader2 className="animate-spin"/> Anmeldung wird geprüft …</div>:status==='error'?<><p className="error" role="alert">{error}</p><Button onClick={()=>{setStatus('loading');check()}}>Erneut versuchen</Button></>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error||'Anmeldung fehlgeschlagen.');setPassword('');setStatus('signedin')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label htmlFor="username">Benutzername</label><Input id="username" autoComplete="username" required maxLength={100} value={username} onChange={e=>setUsername(e.target.value)} placeholder="Dein Benutzername"/><label htmlFor="password">Passwort</label><Input id="password" type="password" autoComplete="current-password" required maxLength={256} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Dein Passwort"/>{error&&<p className="error" role="alert">{error}</p>}<Button type="submit" disabled={busy} className="login-submit">{busy?'Anmelden …':'Einloggen'}<ArrowRight/></Button></form>}<div className="login-foot">NBA 2026/27 · Dein privater Fanbereich</div></Reveal></div><p className="login-bottom">30 Teams. Eine Liga.</p></div>
}
