'use client';
import {motion,MotionConfig,AnimatePresence,useReducedMotion} from 'motion/react';
import {ComponentProps,ReactNode,CSSProperties} from 'react';
import {TabsContent} from '@/components/ui/tabs';
export function MotionRoot({children}:{children:ReactNode}){return <MotionConfig reducedMotion="user" transition={{type:'spring',stiffness:330,damping:30}}>{children}</MotionConfig>}
export function Reveal({children,className,delay=0}:{children:ReactNode;className?:string;delay?:number}){const reduce=useReducedMotion();return <motion.div className={className} initial={{opacity:0,y:reduce?0:16}} animate={{opacity:1,y:0}} transition={{duration:reduce?0:.48,delay:reduce?0:delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
export function AnimatedTab(props:ComponentProps<typeof TabsContent>){const reduce=useReducedMotion();return <TabsContent {...props} asChild><motion.div initial={{opacity:0,y:reduce?0:12}} animate={{opacity:1,y:0}} transition={{duration:reduce?0:.28}}>{props.children}</motion.div></TabsContent>}
export function ClubCard({children,index,color}:{children:ReactNode;index:number;color:string}){const reduce=useReducedMotion();return <motion.article className="team-card" layout="position" style={{'--club':color} as CSSProperties} initial={{opacity:0,y:reduce?0:22}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:reduce?1:.96}} transition={{opacity:{duration:.3,delay:reduce?0:Math.min(index,7)*.035},y:{duration:.4,delay:reduce?0:Math.min(index,7)*.035},layout:{duration:reduce?0:.3}}} whileHover={reduce?{}:{y:-5}} onPointerMove={e=>{if(e.pointerType==='touch'||reduce)return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--pointer-x',`${e.clientX-r.left}px`);e.currentTarget.style.setProperty('--pointer-y',`${e.clientY-r.top}px`)}}>{children}</motion.article>}
export function Count({value}:{value:number}){const reduce=useReducedMotion();return <span className="animated-count"><AnimatePresence mode="popLayout" initial={false}><motion.span key={value} initial={{opacity:0,y:reduce?0:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:reduce?0:-12}} transition={{duration:reduce?0:.22}}>{value.toString().padStart(2,'0')}</motion.span></AnimatePresence></span>}
export {motion,AnimatePresence};
